name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Backend Setup
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Backend
      working-directory: backend
      run: mvn clean package -DskipTests

    # Frontend Setup
    - name: Set up Node.js 19
      uses: actions/setup-node@v4
      with:
        node-version: '19'

    - name: Install Frontend Dependencies
      working-directory: frontend
      run: npm install

    - name: Build Frontend
      working-directory: frontend
      run: npm run build

    # (Optional) Run Backend Tests
    - name: Run Backend Tests
      working-directory: backend
      run: mvn test

    # (Optional) Run Frontend Tests
    - name: Run Frontend Tests
      working-directory: frontend
      run: npm run test

    # (Optional) Docker Build
    - name: Build Docker Images
      run: docker-compose build
